spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:mysql://localhost:3306/ponto_inteligente
    username: root
    password: Dfreitas2466
